In [1]:
import numpy as np
import pandas as pd

In [2]:
company=pd.read_csv('companies.csv')

In [3]:
company

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
496,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
497,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
498,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
499,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

In [4]:
delivery=pd.read_csv('deliveries.csv')
delivery

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [5]:
#to get top 5 most run scoring batsmen 
runs=delivery.groupby('batsman')

In [6]:
runs['batsman_runs'].sum().sort_values(ascending=False)

batsman
SK Raina        4548
V Kohli         4423
RG Sharma       4207
G Gambhir       4132
DA Warner       4014
                ...
Abdur Razzak       0
S Kaushik          0
S Ladda            0
U Kaul             0
RR Bhatkal         0
Name: batsman_runs, Length: 461, dtype: int64

In [7]:
#to print batsmen with max. number of fours
mask=delivery['batsman_runs']==4
new_delivery=delivery[mask]

In [8]:
#total number of fours
new_delivery.shape[0]

17033

In [9]:
new_delivery.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

batsman
G Gambhir    484
SK Raina     402
DA Warner    401
S Dhawan     401
V Kohli      384
Name: batsman_runs, dtype: int64

In [10]:
#to find which teams has virat scored the maximum runs against 
mask1=delivery['batsman']=='V Kohli'
new_delivery1=delivery[mask1]

In [11]:
new_delivery1.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False)

bowling_team
Chennai Super Kings        706
Delhi Daredevils           661
Kings XI Punjab            483
Mumbai Indians             447
Sunrisers Hyderabad        439
Kolkata Knight Riders      391
Deccan Chargers            306
Gujarat Lions              283
Rajasthan Royals           258
Rising Pune Supergiants    188
Pune Warriors              128
Rising Pune Supergiant      83
Kochi Tuskers Kerala        50
Name: batsman_runs, dtype: int64

In [12]:
new_delivery1.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).index[0]

'Chennai Super Kings'

In [13]:
#isin() function to find the most hitting death over batsman
#strike rate=number of runs/number of balls *100
# min batsman 200 balls in over 16-20
mask=delivery['over']>15
death_over=delivery[mask]

In [14]:
all_batsman=death_over.groupby('batsman')['batsman_runs'].count()
x=all_batsman>200     #this is a good way to represent 
batsman_list=all_batsman[x].index.tolist()

In [15]:
final=death_over[death_over['batsman'].isin(batsman_list)]

In [16]:
runs=final.groupby('batsman')['batsman_runs'].sum()

In [17]:
balls=final.groupby('batsman')['batsman_runs'].count()

In [18]:
sr=(runs/balls)*100

In [19]:
sr.sort_values(ascending=False)

batsman
AB de Villiers      211.052632
DA Warner           189.473684
DA Miller           186.666667
V Kohli             181.868132
RG Sharma           175.668449
DJ Hussey           175.213675
RV Uthappa          173.454545
Yuvraj Singh        171.124031
JH Kallis           170.562771
MS Dhoni            169.607843
SPD Smith           169.303797
JP Duminy           167.760618
DJ Bravo            167.726161
SK Raina            167.467249
AT Rayudu           165.411765
WP Saha             163.389831
KA Pollard          161.336516
YK Pathan           159.246575
S Dhawan            158.847737
BJ Hodge            157.402597
AM Rahane           152.985075
LRPL Taylor         152.941176
KD Karthik          152.051836
DPMD Jayawardene    152.032520
MK Pandey           151.785714
JA Morkel           149.882353
JP Faulkner         149.319728
S Badrinath         149.116608
Y Venugopal Rao     148.846154
Harbhajan Singh     147.607656
AD Mathews          147.058824
KM Jadhav           144.378698
STR Binny           144.036697
AR Patel            142.794760
IK Pathan           142.580645
MK Tiwary           140.189125
SS Tiwary           136.666667
NV Ojha             134.868421
RA Jadeja           130.729167
PP Chawla           120.257235
P Kumar             109.701493
R Vinay Kumar       108.936170
A Mishra            100.888889
Name: batsman_runs, dtype: float64